---
title: "Check bibliography output"
output: 
  # pdf_document
  word_document
date: "`r paste0(format(Sys.time(), '%B %d, %Y'))`"
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/apa-no-ampersand.csl"
bibliography: "../cite/bibliography.bib"
---


```{r, echo = FALSE}
bibfiletext <- readLines(con = paste0("../cite/bibliography.bib"))
library(magrittr)

output_citations <- function(bibfiletext, 
                             year = NULL, 
                             author_last = NULL) {
  
  bibfiletext0 <- bibfiletext00 <- bibfiletext
  cite_start <- grep(pattern = "@", x = bibfiletext0, fixed = TRUE)
  
  # # pull out data for speific years
  # cite_start0 <- c()
  # if (!is.null(year)) {
  #   for (i in 1:length(year)){
  #     cite_year <- grep(pattern = paste0("year = {",year[i],"}"), 
  #                       x = bibfiletext0, fixed = TRUE)
  #     cite_year0 <- c()
  #     for (ii in 1:length(cite_year)) {
  #       temp <- which(cite_start<cite_year[ii])
  #       cite_year0 <- c(cite_year0, 
  #                       cite_start[length(temp)])
  #     }
  #     cite_start0 <- c(cite_start0, cite_year0)
  #   }
  #  cite_start <- cite_start0
  # }
  # 
  
  # # pull out data for speific authors
  # cite_start0 <- c()
  # if (!is.null(author_last)) {
  #   for (i in 1:length(year)){
  #     cite_author <- grep(pattern = paste0("author = {",author_last[i],"}"), 
  #                       x = bibfiletext0, fixed = TRUE)
  #     cite_author0 <- c()
  #     for (ii in 1:length(cite_author)) {
  #       temp <- which(cite_start<cite_author[ii])
  #       cite_author0 <- c(cite_author0, 
  #                       cite_start[length(temp)])
  #     }
  #     cite_start0 <- c(cite_start0, cite_author0)
  #   }
  #  cite_start <- cite_start0
  # }
  
  # cite_start <- unique(cite_start)
  
bibfiletext0 <- bibfiletext0[cite_start]
bibfiletext0 <- unlist(lapply(X = strsplit(split = "{", x = bibfiletext0, fixed = TRUE), "[[", 2))
bibfiletext0 <- gsub(pattern = ",", replacement = "", x = bibfiletext0, fixed = TRUE)
bibfiletext0 <- trimws(bibfiletext0)

# find author and year order
  cite_auth <- bibfiletext00[grep(pattern = "author = {", x = bibfiletext00, fixed = TRUE)]
  cite_auth <- gsub(pattern = " = {{", replacement = " = {", x = cite_auth, fixed = TRUE)
  cite_auth <- unlist(lapply(X = strsplit(split = "{", x = cite_auth, fixed = TRUE), "[[", 2))

  cite_yr <- bibfiletext00[grep(pattern = "year = {", x = bibfiletext00, fixed = TRUE)]
  cite_yr <- unlist(lapply(X = strsplit(split = "{", x = cite_yr, fixed = TRUE), "[[", 2))


  bibfiletext1 <- data.frame(
    rn = bibfiletext0, 
    auth = cite_auth, 
    year = cite_yr) %>% 
    dplyr::arrange(auth, year)
  
b <- unlist(paste0(
            "@", unlist(bibfiletext1), 
"

", 
            collapse = ""))
return(b)
}

b <- output_citations(bibfiletext = bibfiletext)
```

## All in-line text citations

`r b`

## Works cited

<div id="refs"></div>

## All in-line text citations from 2022

```{r, echo = FALSE, eval=FALSE}
# Test
b <- output_citations(bibfiletext = bibfiletext, year = 2021:2022)
```

`r b`



